const { FeeEstimator } = require("./fee");
const {
  SimpleTxBuilder,
  getDeploymentInfo,
  getContractCellDep,
  SimpleClient,
  calculateMinimumCapacity,
  validatePrivateKey,
} = require("./txbuilder");

const {
  FACTORY_DATA_SIZE,
  DEX_INSTANCE_SIZE,
  DEX_DATA_SIZE,
  DEFAULT_FACTORY_CONFIG,
  DEFAULT_DEX_FEE_BPS,
  DEX_STATUS_ACTIVE,
  DEX_STATUS_SUSPENDED,
  DEX_STATUS_DELISTED,
  createFactoryConfig,
  encodeFactoryData,
  decodeFactoryData,
  encodeDexInstanceData,
  decodeDexInstanceData,
  encodeDexData,
  decodeDexData,
  encodePoolData,
  decodePoolData,
  calculateFeeBreakdown,
  calculateSwapFees,
  calculateInitialLP,
  hashDexName,
  generateDexId,
  validateBytes32,
  validateDexName,
  checkActivityRequirements,
} = require("./factory");

const {
  MINIMUM_LIQUIDITY,
  MAX_FEE_BPS,
  DEFAULT_FEE_BPS,
  POOL_DATA_SIZE,
  VAULT_DATA_SIZE,
  DEFAULT_LP_FEE_BPS,
  DEFAULT_OPERATOR_FEE_BPS,
  DEFAULT_PROTOCOL_FEE_BPS,
  calculateSwapOutput,
  calculateLiquidityMint,
  calculateLiquidityRemove,
  calculateK,
  validateKInvariant,
  createVault,
  addFees,
  calculateLpShare,
  calculateOperatorShare,
  calculateProtocolShare,
  recordDistribution,
  getDistributableFees,
  hasFeesToDistribute,
  encodeVaultData,
  decodeVaultData,
  getFeeBreakdown,
} = require("./pool");

const {
  DCURVE_DATA_SIZE,
  PRICE_MULTIPLIER_DISCOUNT,
  PRICE_MULTIPLIER_BASELINE,
  PRICE_MULTIPLIER_PREMIUM,
  CURVE_STATUS_PENDING,
  CURVE_STATUS_ACTIVE,
  CURVE_STATUS_FILLED,
  CURVE_STATUS_SUCCESS,
  CURVE_STATUS_EXPIRED,
  CURVE_STATUS_REFUNDED,
  calculateCurvePrice,
  calculateTokensForCkb,
  calculateCkbForTokens,
  calculatePriceImpact,
  calculateArbitrageOpportunity,
  formatPrice,
  createCurveConfig,
  encodeCurveData,
  decodeCurveData,
  determineCurveStatus,
  isCurveActive,
  isCurveFilled,
  isCurveExpired,
  isWithinContributionWindow,
} = require("./curve");

const launchpad = require("./launchpad");
const {
  LAUNCH_DATA_SIZE,
  STATUS_PENDING,
  STATUS_ACTIVE,
  STATUS_SUCCESS,
  STATUS_EXPIRED,
  STATUS_CANCELLED,
  DEFAULT_PRICE_MULTIPLIER_BPS,
  createLaunchConfig,
  encodeLaunchConfig,
  decodeLaunchConfig,
  determineStatus,
  isValidTransition,
  generateLaunchId,
  buildCreateLaunchTx,
  buildContributeTx,
  buildFinalizeTx,
  buildClaimLpTx,
  buildRefundTx,
  buildDistributeFeesTx,
  validateLockScriptHash,
} = launchpad;

const {
  REFUND_DATA_SIZE,
  HASH_SIZE,
  REFUND_STATUS_PENDING,
  REFUND_STATUS_ACTIVE,
  REFUND_STATUS_COMPLETED,
  createRefundClaim,
  encodeRefundClaim,
  decodeRefundClaim,
  buildWitnessData,
  determineRefundStatus,
  isRefundActive,
  hashPair,
  generateMerkleRoot,
  generateMerkleProof,
  verifyMerkleProof,
  createClaimLeaf,
  generateBatchProofs,
} = require("./refund");

const {
  serializeClaim,
  encodeProof,
  decodeProof,
  formatProof,
  MAX_PROOF_DEPTH,
} = require("./proof");

module.exports = {
  FeeEstimator,
  SimpleTxBuilder,
  SimpleClient,
  calculateMinimumCapacity,
  validatePrivateKey,
  getDeploymentInfo,
  getContractCellDep,

  FACTORY_DATA_SIZE,
  DEX_INSTANCE_SIZE,
  DEX_DATA_SIZE,
  DEFAULT_FACTORY_CONFIG,
  DEFAULT_DEX_FEE_BPS,
  DEX_STATUS_ACTIVE,
  DEX_STATUS_SUSPENDED,
  DEX_STATUS_DELISTED,
  createFactoryConfig,
  encodeFactoryData,
  decodeFactoryData,
  encodeDexInstanceData,
  decodeDexInstanceData,
  encodeDexData,
  decodeDexData,
  encodePoolData,
  decodePoolData,
  calculateFeeBreakdown,
  calculateSwapFees,
  calculateInitialLP,
  hashDexName,
  generateDexId,
  validateBytes32,
  validateDexName,
  checkActivityRequirements,

  MINIMUM_LIQUIDITY,
  MAX_FEE_BPS,
  DEFAULT_FEE_BPS,
  POOL_DATA_SIZE,
  VAULT_DATA_SIZE,
  DEFAULT_LP_FEE_BPS,
  DEFAULT_OPERATOR_FEE_BPS,
  DEFAULT_PROTOCOL_FEE_BPS,
  calculateSwapOutput,
  calculateLiquidityMint,
  calculateLiquidityRemove,
  calculateK,
  validateKInvariant,
  createVault,
  addFees,
  calculateLpShare,
  calculateOperatorShare,
  calculateProtocolShare,
  recordDistribution,
  getDistributableFees,
  hasFeesToDistribute,
  encodeVaultData,
  decodeVaultData,
  getFeeBreakdown,

  DCURVE_DATA_SIZE,
  PRICE_MULTIPLIER_DISCOUNT,
  PRICE_MULTIPLIER_BASELINE,
  PRICE_MULTIPLIER_PREMIUM,
  CURVE_STATUS_PENDING,
  CURVE_STATUS_ACTIVE,
  CURVE_STATUS_FILLED,
  CURVE_STATUS_SUCCESS,
  CURVE_STATUS_EXPIRED,
  CURVE_STATUS_REFUNDED,
  calculateCurvePrice,
  calculateTokensForCkb,
  calculateCkbForTokens,
  calculateArbitrageOpportunity,
  formatPrice,
  createCurveConfig,
  encodeCurveData,
  decodeCurveData,
  determineCurveStatus,
  isCurveActive,
  isCurveFilled,
  isCurveExpired,
  isWithinContributionWindow,

  LAUNCH_DATA_SIZE,
  STATUS_PENDING,
  STATUS_ACTIVE,
  STATUS_SUCCESS,
  STATUS_EXPIRED,
  STATUS_CANCELLED,
  DEFAULT_PRICE_MULTIPLIER_BPS,
  createLaunchConfig,
  encodeLaunchConfig,
  decodeLaunchConfig,
  isLaunchWithinContributionWindow: launchpad.isWithinContributionWindow,
  determineStatus,
  isValidTransition,
  generateLaunchId,
  buildCreateLaunchTx,
  buildContributeTx,
  buildFinalizeTx,
  buildClaimLpTx,
  buildRefundTx,
  buildDistributeFeesTx,
  validateLockScriptHash,

  REFUND_DATA_SIZE,
  HASH_SIZE,
  REFUND_STATUS_PENDING,
  REFUND_STATUS_ACTIVE,
  REFUND_STATUS_COMPLETED,
  createRefundClaim,
  encodeRefundClaim,
  decodeRefundClaim,
  buildWitnessData,
  determineRefundStatus,
  isRefundActive,

  hashPair,
  generateMerkleRoot,
  generateMerkleProof,
  verifyMerkleProof,
  serializeClaim,
  createClaimLeaf,
  generateBatchProofs,
  encodeProof,
  decodeProof,
  formatProof,
  MAX_PROOF_DEPTH,
};
